services:
  # consul:
  #   image: "consul:1.15.4"
  #   ports:
  #     - "8500:8500"
  etcd:
    image: bitnami/etcd:3.5
    ports:
      - 2379:2379
      # - 2380:2380
    volumes:
      - ./etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asiz/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"